import withAuth from "@/components/Auth/withAuth";
import DataEvents from "@/components/admin/DataEvents";
import Navbar from "@/components/admin/Navbar";
import Sidebar from "@/components/admin/Sidebar";
import TitleTeam, { getHeaderTeam, getListTeam } from "@/components/admin/TitleTeam";
import fetcher from "@/helpers/fetcher";
import styles from "@/styles/Main.module.scss";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { RingLoader } from "react-spinners";

const API_URL = process.env.NEXT_PUBLIC_API_URL;

const Events = () => {
  const [selectedRows, setSelectedRows] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [data, setData] = useState([]);
  const [header, setHeader] = useState([]);
  
  useEffect(() => {
    getHeaderTeam().then((result) => {
      setHeader(result);
    });
    getListTeam().then((result) => {
      setData(result);
      setIsLoading(false)
    });
  }, []);
  const handleSaveListChanges = () => {
    getListTeam().then((result) => {
      setData(result);
    });
  };
  const handleSaveTitleChanges = () => {
    getHeaderTeam().then((result) => {
      setHeader(result);
    });
  };
  return (
    <div className={styles.body}>
      <Head>
        <title>{process.env.NEXT_PUBLIC_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/svg/logo.svg" />
      </Head>
      {isLoading ? (
        <div className="fixed inset-0 flex items-center justify-center z-50 bg-black font-semibold text-xl text-white">
          <RingLoader color="#0894da" size={80} /> Loading...
        </div>
      ) : (
        <>
          <Navbar />
          <Sidebar />
          <div className="bg-gray-900 pt-10 ml-52">
            <DataEvents data={data} onSave={handleSaveListChanges} />
          </div>

        </>
      )}
    </div>
  );
};

export default withAuth(Events);
