import withAuth from "@/components/Auth/withAuth";
import Navbar from "@/components/admin/Navbar";
import Sidebar from "@/components/admin/Sidebar";
import styles from "@/styles/Main.module.scss";
import Head from "next/head";
import { useState } from "react";

const OurTeam = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const handleEditClick = () => {
    setIsModalOpen(true);
  };

  const handleModalClose = () => {
    setIsModalOpen(false);
  };


  return (
    <div className={styles.body}>
      <Head>
        <title>{process.env.NEXT_PUBLIC_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/svg/logo.svg" />
      </Head>
      <Navbar />
      <Sidebar />
      <div className="bg-gray-900 pt-10 ml-52">
      <div className="md:col-span-2 xl:col-span-3 flex justify-center items-center">
        <h1 className="text-center text-white font-bold text-xl mb-4">
        Pusinfomar TNI Core team
        </h1>

        <button
          className="bg-blue-500 text-white px-5 py-2 mb-3 absolute right-[230px] rounded"
          onClick={handleEditClick}
        >
          Edit
        </button>
      </div>
        <div className="flex items-center justify-center mt-2">
          <img
            src="https://www.ifc.org.sg/ifc2web/images/refresh/RSN/IFCChart.png"
            style={{ width: 700 }}
            alt="Logo"
          />
        </div>
      </div>
      {isModalOpen && (
        <div className="fixed top-0 left-0 w-full h-full flex items-center justify-center z-50">
          <div className="fixed top-0 left-0 w-full h-full bg-black opacity-50"></div>
          <div
            className="dark:bg-gray-800 rounded-lg z-10 absolute p-4 w-[700px] shadow-md"
            style={{ maxHeight: 600 }}
          >
            <form >
              <div className="mb-4">
                <label className="block text-gray-200 text-sm font-bold mb-2">
                  New Title:
                </label>
                <input
                  type="text"
                  className="appearance-none w-full py-2 px-3 text-gray-200 leading-tight focus:outline-none focus:shadow-outline bg-gray-600 rounded"
                />
              </div>
              <div className="mb-4">
                  <label className="block text-gray-200 text-sm font-bold mb-2">
                    New Image File:
                  </label>
                  <input
                    type="file"
                    accept="image/*"
                    name="file"
                    className="appearance-none w-full py-2 px-3 text-gray-200 leading-tight focus:outline-none focus:shadow-outline"
                  />
                </div>
              <div className="flex justify-end">
                <button
                  onClick={handleModalClose}
                  className="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded mr-2"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded"
                >
                  Save Changes
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default withAuth(OurTeam);
