import withAuth from "@/components/Auth/withAuth";
import Navbar from "@/components/admin/Navbar";
import Sidebar from "@/components/admin/Sidebar";
import fetcher from "@/helpers/fetcher";
import styles from "@/styles/Main.module.scss";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import DataTable from "react-data-table-component";
import { RingLoader } from "react-spinners";

const API_URL = process.env.NEXT_PUBLIC_API_URL;

export const getListTeam = async () => {
  const params = {
    method: "GET",
    url: API_URL + "team/list",
    type: "json",
  };
  return await fetcher(params).then((json) => (json ? json : []));
};

const OurTeam = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedRows, setSelectedRows] = useState([]);
  const [data, setData] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    getListTeam().then((result) => {
      setData(result);
      setIsLoading(false);
    });
  }, []);
  const handleEditClick = () => {
    setIsModalOpen(true);
  };

  const handleModalClose = () => {
    setIsModalOpen(false);
  };

  const columns = [
    {
      name: "Name",
      selector: "name",
      sortable: true,
    },
    {
      name: "Description",
      selector: "description",
      sortable: true,
    },
    {
      name: "Path",
      selector: "image",
      sortable: true,
    },
    {
      name: "Actions",
      cell: (row) => (
        <div>
          <button
            // onClick={() => handleEditClick(row)} // Tambahkan fungsi edit di sini
            className="bg-blue-500 text-white px-2 py-1 mx-1 rounded"
          >
            Edit
          </button>
          <button
            // onClick={() => handleDeleteClick(row)} // Tambahkan fungsi delete di sini
            className="bg-red-500 text-white px-2 py-1 mx-1 rounded"
          >
            Delete
          </button>
        </div>
      ),
    },
  ];

  const customTitleStyles = {
    backgroundColor: "#111827", // Ganti dengan warna bg-dark-900 yang sesuai
    padding: "15px 15px", // Sesuaikan sesuai dengan kebutuhan Anda
    textAlign: "center",
    marginLeft: "-20px",
    marginRight: "-20px",
    color: "white",
  };
  const customStyles = {
    headRow: {
      style: {
        backgroundColor: "#111827",
        color: "white",
      },
    },
    rows: {
      style: {
        backgroundColor: "#111827",
        color: "white",
      },
    },
  };
  return (
    <div className={styles.body}>
      <Head>
        <title>{process.env.NEXT_PUBLIC_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/svg/logo.svg" />
      </Head>
      {isLoading ? (
        <div className="fixed inset-0 flex items-center justify-center z-50 bg-black font-semibold text-xl text-white">
          <RingLoader color="#0894da" size={80} /> Loading...
        </div>
      ) : (
        <>
          <Navbar />
          <Sidebar />
          <div className="bg-gray-900 pt-10 ml-52">
            <div className="md:col-span-2 xl:col-span-3 flex justify-center items-center">
              <h1 className="text-center text-white font-bold text-xl mb-4">
                Pusinfomar TNI Core team
              </h1>

              <button
                className="bg-blue-500 text-white px-5 py-2 mb-3 absolute right-[230px] rounded"
                onClick={handleEditClick}
              >
                Edit
              </button>
            </div>
            <div className="flex items-center justify-center mt-2">
              <img
                src="https://www.ifc.org.sg/ifc2web/images/refresh/RSN/IFCChart.png"
                style={{ width: 700 }}
                alt="Logo"
              />
            </div>
            <div className="w-[900px] mx-auto my-10 bg-gray-900">
              <DataTable
                title={
                  <div style={customTitleStyles}>
                    <h1 className="text-center font-semibold">Our Team List</h1>
                  </div>
                }
                columns={columns}
                data={data}
                customStyles={customStyles}
                pagination
                paginationPerPage={10}
                paginationRowsPerPageOptions={[10, 20, 30]}
                paginationComponentOptions={{
                  rowsPerPageText: "Rows per page:",
                }}
                theme="dark"
              />
            </div>
          </div>
          {isModalOpen && (
            <div className="fixed top-0 left-0 w-full h-full flex items-center justify-center z-50">
              <div className="fixed top-0 left-0 w-full h-full bg-black opacity-50"></div>
              <div
                className="dark:bg-gray-800 rounded-lg z-10 absolute p-4 w-[700px] shadow-md"
                style={{ maxHeight: 600 }}
              >
                <form>
                  <div className="mb-4">
                    <label className="block text-gray-200 text-sm font-bold mb-2">
                      New Title:
                    </label>
                    <input
                      type="text"
                      className="appearance-none w-full py-2 px-3 text-gray-200 leading-tight focus:outline-none focus:shadow-outline bg-gray-600 rounded"
                    />
                  </div>
                  <div className="mb-4">
                    <label className="block text-gray-200 text-sm font-bold mb-2">
                      New Image File:
                    </label>
                    <input
                      type="file"
                      accept="image/*"
                      name="file"
                      className="appearance-none w-full py-2 px-3 text-gray-200 leading-tight focus:outline-none focus:shadow-outline"
                    />
                  </div>
                  <div className="flex justify-end">
                    <button
                      onClick={handleModalClose}
                      className="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded mr-2"
                    >
                      Cancel
                    </button>
                    <button
                      type="submit"
                      className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded"
                    >
                      Save Changes
                    </button>
                  </div>
                </form>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
};

export default withAuth(OurTeam);
