import Navbar from "@/components/Navbar";
import React, { useEffect, useState } from "react";
import styles from "@/styles/Main.module.scss";
import CarouselSmall from "@/components/CarouselSmall";
import Breadcrumbs from "@/components/Breadcrumbs";
import Head from "next/head";
import Foreword from "@/components/Foreword";
import AboutSection from "@/components/AboutSection";
import MissionSection from "@/components/MissionSection";
import VisionSection from "@/components/VIsionSection";
import Footer from "@/components/Footer";
import { getAboutDescData, getForewordData, getMissionData, getVisionData } from "./admin/about";
import { RingLoader } from "react-spinners";
import { getHeaderImage } from "./our-team";

const AboutUs = () => {
  const [forewordData, setForewordData] = useState([]);
  const [aboutData, setAboutData] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [missionData, setMissionData] = useState([]);
  const [visionData, setVisionData] = useState([]);

  const [carouselImg, setCarouselImg] = useState(null);
  const breadcrumbs = [
    { text: "Home", link: "/" },
    { text: "About", link: "/about" },
    { text: "About Us" },
  ];

  useEffect(() => {
    getForewordData().then((result) => {
      setForewordData(result);
      getAboutDescData().then((result) => {
        setAboutData(result);
        getMissionData().then((result) => {
          setMissionData(result);
          getVisionData().then((result) => {
            setVisionData(result);
            getHeaderImage(1).then((result) => {
              setCarouselImg(result);
            })
          });
        });
      });
    });
  }, []);
  useEffect(() => {
    if (forewordData.length > 0 && aboutData.length > 0 && missionData.length > 0 && visionData.length > 0) {
      setIsLoading(false);
    }
  }, [forewordData, aboutData, missionData, visionData]);
  const newsData = {
    title: "Our Journey",
    newsItems: [
      {
        year: 1,
        imageSrc: "https://via.placeholder.com/400x200", // Dummy image URL for year 1
        explanation: "Explanation for year 1...",
      },
      {
        year: 2,
        imageSrc: "https://via.placeholder.com/400x200", // Dummy image URL for year 2
        explanation: "Explanation for year 2...",
      },
      // Add more news items as needed
    ],
  };
  const titlePage = "";
  return (
    <div className={styles.body}>
      <Head>
        <title>{process.env.NEXT_PUBLIC_NAME} - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/svg/logo.svg" />
      </Head>
      {isLoading ? (
        <div className="fixed inset-0 flex items-center justify-center z-50 bg-black font-semibold text-xl text-white">
          <RingLoader color="#0894da" size={80} /> Loading...
        </div>
      ) : (
        <>
          <Navbar />
          <CarouselSmall headerImg={carouselImg} titlePage={titlePage} />
          <Breadcrumbs data={breadcrumbs} />
          <Foreword data={forewordData} />
          <AboutSection data={aboutData} />
          <MissionSection data={missionData} />
          <VisionSection data={visionData} />
          <Footer></Footer>
        </>
      )}
    </div>
  );
};

export default AboutUs;
