import Navbar from "@/components/Navbar";
import React from "react";
import styles from "@/styles/Main.module.scss"
import CarouselSmall from "@/components/CarouselSmall";
import Breadcrumbs from "@/components/Breadcrumbs";
import Head from "next/head";
import CardGallery from "@/components/CardGallery";

const Gallery = () => {
    const titlePage = "GALLERY"
    const carouselImg = '/img/jpg/gallery.jpg'
    const breadcrumbs = [
        { text: 'Home', link: '/' },
        { text: 'Gallery' },
    ];
    const cardData = [
        { title: 'Card Title 1', imageUrl: 'https://via.placeholder.com/400x200' },
        { title: 'Card Title 2', imageUrl: 'https://via.placeholder.com/400x200' },
        { title: 'Card Title 3', imageUrl: 'https://via.placeholder.com/400x200' },
        { title: 'Card Title 4', imageUrl: 'https://via.placeholder.com/400x200' },
        { title: 'Card Title 5', imageUrl: 'https://via.placeholder.com/400x200' },
        { title: 'Card Title 6', imageUrl: 'https://via.placeholder.com/400x200' },
        { title: 'Card Title 7', imageUrl: 'https://via.placeholder.com/400x200' },
        { title: 'Card Title 8', imageUrl: 'https://via.placeholder.com/400x200' },
        { title: 'Card Title 9', imageUrl: 'https://via.placeholder.com/400x200' },
        // ... Add more card data here ...
      ];

      console.log(cardData)
    
    return (
    <div className={styles.body}>
        <Head>
        <title>{process.env.NEXT_PUBLIC_NAME} - Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/svg/logo.svg" />
      </Head>
        <Navbar />
        <CarouselSmall headerImg={carouselImg} titlePage={titlePage}/>
        <Breadcrumbs data={breadcrumbs} />
        <CardGallery data={cardData} />
    </div>
    )
}

export default Gallery;