import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import styles from '@/styles/Main.module.scss'
import Navbar from '@/components/Navbar';
import CarouselBig from '@/components/CarouselBig';
import WhatsNew from '@/components/WhatsNew';
import IntroSection from '@/components/IntroSection';
import QuickLinks from '@/components/QuickLinks';
import Footer from '@/components/Footer';
import fetcher from '@/helpers/fetcher';

export const getWelcomeData = async () => {
  const API_URL = process.env.NEXT_PUBLIC_API_URL
  const params = {
    method: "GET",
    url:  API_URL + "",
    type: "json",
  };
  return await fetcher(params).then(json => (json ? json : []));
};

const Home = () => {
  const [welcomeData, setWelcomeData] = useState([])

  const cardData = [
    { title: 'Card Title 1', imageUrl: '/img/jpg/CardTitle.jpeg' },
    { title: 'Card Title 2', imageUrl: '/img/jpg/CardTitle.jpeg' },
    { title: 'Card Title 3', imageUrl: '/img/jpg/CardTitle.jpeg' },
    { title: 'Card Title 3', imageUrl: '/img/jpg/CardTitle.jpeg' },
    { title: 'Card Title 3', imageUrl: '/img/jpg/CardTitle.jpeg' },
    { title: 'Card Title 3', imageUrl: '/img/jpg/CardTitle.jpeg' },
  ];

  useEffect(() => {
    getWelcomeData().then(result => {
      setWelcomeData(result[0]);
    });
  }, []);

  return (
    <div className={styles.body}>
      <Head>
        <title>{process.env.NEXT_PUBLIC_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/svg/logo.svg" />
      </Head>

      {/* Your HTML content */}
      {/* ... (Paste your HTML content here) */}
      <Navbar></Navbar>
      <CarouselBig></CarouselBig>
      <WhatsNew data={cardData}></WhatsNew>
      <IntroSection
        {...welcomeData}
      />
      <QuickLinks></QuickLinks>
      <Footer></Footer>
    </div>
  );
};

export default Home;
