import Navbar from "@/components/Navbar";
import React, { use, useEffect, useState } from "react";
import styles from "@/styles/Main.module.scss";
import CarouselSmall from "@/components/CarouselSmall";
import Breadcrumbs from "@/components/Breadcrumbs";
import Head from "next/head";
import ListOurTeam from "@/components/ListOurTeam";
import Footer from "@/components/Footer";
import { getHeaderTeam, getListTeam } from "@/components/admin/TitleTeam";
import { RingLoader } from "react-spinners";

const API_URL = process.env.NEXT_PUBLIC_API_URL;

export const getHeaderImage = async (id) => {
  const body = new FormData();
  let response;
  body.append("id", id);

  response = await fetch(API_URL + "settings/detailItem", {
    method: "POST",
    body,
  });

  const data = await response.json();
  if (response.ok) {
    return data[0].image;
  }
};


const OurTeam = () => {
  const [data, setData] = useState([]);
  const [header, setHeader] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [carouselImg, setCarouselImg] = useState(null);

  useEffect(() => {
    getHeaderTeam().then((result) => {
      setHeader(result);
      getListTeam().then((result) => {
        setData(result);
        getHeaderImage(2).then((result) => {
          setCarouselImg(result)
          setIsLoading(false);
        })
      });
    });
  }, []);

  const breadcrumbs = [
    { text: "Home", link: "/" },
    { text: "About", link: "/about" },
    { text: "Our Team" },
  ];
  const titlePage = "";
  return (
    <div className={styles.body}>
      <Head>
        <title>{process.env.NEXT_PUBLIC_NAME} - Our Team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/svg/logo.svg" />
      </Head>

      {isLoading ? (
        <div className="fixed inset-0 flex items-center justify-center z-50 bg-black font-semibold text-xl text-white">
          <RingLoader color="#0894da" size={80} /> Loading...
        </div>
      ) : (
        <>
          <Navbar />
          <CarouselSmall headerImg={carouselImg} titlePage={titlePage} />
          <Breadcrumbs data={breadcrumbs} />
          <div className="mx-auto">
            <br />
            <br />
            <br />
            <div className="text-3xl font-semibold text-center text-gray-500">
              {header[0].title}
            </div>
            <div className="flex items-center justify-center mt-16">
              <img
                src={API_URL + "uploads/" + header[0].image}
                style={{ width: 1000 }}
                alt="Logo"
              />
            </div>
            <ListOurTeam listData={data} />
          </div>
        </>
      )}
      <Footer></Footer>
    </div>
  );
};

export default OurTeam;
