import Navbar from "@/components/Navbar";
import React from "react";
import styles from "@/styles/Main.module.scss";
import CarouselSmall from "@/components/CarouselSmall";
import Breadcrumbs from "@/components/Breadcrumbs";
import Head from "next/head";
import Foreword from "@/components/Foreword";
import AboutSection from "@/components/AboutSection";
import MissionSection from "@/components/MissionSection";
import VisionSection from "@/components/VIsionSection";
import OurNewsSection from "@/components/OurNewsSection";

const OurTeam = () => {
  const carouselImg =
    "https://www.shipspotting.com/photos/middle/7/4/2/3011247.jpg?cb=0";
  const breadcrumbs = [{ text: "Home", link: "/" }, { text: "Our Team" }];
  const titlePage = "OUR TEAM"
  return (
    <div className={styles.body}>
      <Head>
        <title>{process.env.NEXT_PUBLIC_NAME} - Our Team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/svg/logo.svg" />
      </Head>
      <Navbar />
      <CarouselSmall headerImg={carouselImg} titlePage={titlePage} />
      <Breadcrumbs data={breadcrumbs} />
    </div>
  );
};

export default OurTeam;
